//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatcomRfWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblATEOutput
    {
        public long id { get; set; }
        public string ModelSN { get; set; }
        public System.DateTime StartTime { get; set; }
        public string SalesOrder { get; set; }
        public string TestPlan { get; set; }
        public string TestType { get; set; }
        public string TPRev { get; set; }
        public bool Audit { get; set; }
        public bool Itar { get; set; }
        public string RackNum { get; set; }
        public string UserName { get; set; }
        public string LongModelName { get; set; }
        public string TubeSN { get; set; }
        public string TubeName { get; set; }
        public string MainRevision { get; set; }
        public string SsaSN { get; set; }
        public string LinSN { get; set; }
        public string LipaSN { get; set; }
        public Nullable<short> LinGain { get; set; }
        public Nullable<short> LinGainOffset { get; set; }
        public Nullable<short> LinPhase { get; set; }
        public Nullable<short> LinPhaseOffset { get; set; }
        public Nullable<short> LinMag { get; set; }
        public Nullable<short> LinMagOffset { get; set; }
        public Nullable<short> LineVoltage { get; set; }
        public Nullable<short> LineFrequency { get; set; }
        public string IP { get; set; }
        public string MAC { get; set; }
        public string BucSN { get; set; }
        public string BipaSN { get; set; }
        public string BlipaSN { get; set; }
        public string InputStartFrequency { get; set; }
        public string InputStopFrequency { get; set; }
        public string OutputStartFrequency { get; set; }
        public string OutputStopFrequency { get; set; }
        public string RatedPower { get; set; }
    }
}
