//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatcomRfWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCalData
    {
        public long id { get; set; }
        public string AssetNumber { get; set; }
        public double Frequency { get; set; }
        public double CalFactor { get; set; }
        public System.DateTime AddedDate { get; set; }
    }
}
