//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatcomRfWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMonitorData
    {
        public long id { get; set; }
        public string ModelSN { get; set; }
        public System.DateTime StartTime { get; set; }
        public decimal Frequency { get; set; }
        public Nullable<decimal> InputResult { get; set; }
        public Nullable<decimal> OutputResult { get; set; }
        public string Channel { get; set; }
    }
}
