//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatcomRfWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPSCalHeaders
    {
        public long id { get; set; }
        public string AssetNumber { get; set; }
        public string Series { get; set; }
        public string Serial { get; set; }
        public double RefCal { get; set; }
        public string Certificate { get; set; }
        public string Operator { get; set; }
        public System.DateTime CalDate { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string EditedBy { get; set; }
    }
}
